# Generated by Django 2.1 on 2018-11-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30, null=True)),
                ('leader', models.CharField(max_length=50, null=True)),
                ('member1', models.CharField(max_length=50, null=True)),
                ('member2', models.CharField(max_length=50, null=True)),
                ('member3', models.CharField(max_length=50, null=True)),
                ('member_num', models.IntegerField(default=1)),
                ('invite_code', models.CharField(max_length=20, null=True)),
                ('battle_code', models.FileField(null=True, upload_to='')),
                ('battle_time', models.IntegerField(default=1)),
                ('codes', models.TextField(null=True)),
                ('history', models.CharField(default='[]', max_length=8000)),
                ('score', models.CharField(default='[{"score":1000}]', max_length=8000)),
            ],
        ),
    ]
