# Generated by Django 2.1.7 on 2019-03-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Battle ID')),
                ('team_engaged', models.TextField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('robot_num', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('result', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.FileField(upload_to='Files')),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('game_name', models.CharField(max_length=50)),
                ('submission_start', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('student_id', models.CharField(max_length=20, null=True)),
                ('student_nickname', models.CharField(max_length=50, null=True)),
                ('student_realname', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(default='000', max_length=100, null=True)),
                ('salt', models.CharField(max_length=8, null=True)),
                ('thu_email', models.CharField(max_length=100, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=30, null=True, verbose_name='Team name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('captain', models.CharField(max_length=50, null=True, verbose_name='Captain')),
                ('members', models.TextField(default='[]', help_text='Student IDs of team members in JSON array format.  If this is to be modified on django admin site, please make sure it retains valid in JSON format.', verbose_name='Team members')),
                ('member_num', models.IntegerField(default=1, null=True, verbose_name='Members count')),
                ('invitecode', models.CharField(max_length=20, null=True, verbose_name='Invitation code')),
                ('createAt', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('score', models.IntegerField(default=-1)),
                ('rank', models.IntegerField(default=999999)),
                ('battle_code', models.FileField(null=True, upload_to='Codes')),
                ('battle_time', models.IntegerField(default=1)),
                ('codes', models.TextField(null=True)),
                ('history_active', models.TextField(default='[]', help_text='Fighting history records of the team in JSON format.  If this is to be modified on django admin site, please make sure it retains valid in JSON format.', verbose_name='Active fighting history')),
                ('history_passive', models.TextField(default='[]', help_text='Fighting history records of the team in JSON format.  If this is to be modified on django admin site, please make sure it retains valid in JSON format.', verbose_name='Passive fighting history')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Team'),
        ),
    ]
