# Generated by Django 2.1.7 on 2019-03-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='battle_code',
            field=models.FileField(blank=True, null=True, upload_to='Codes'),
        ),
        migrations.AlterField(
            model_name='team',
            name='codes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
