# Generated by Django 2.1 on 2018-11-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('student_id', models.CharField(max_length=20, null=True)),
                ('student_nickname', models.CharField(max_length=50, null=True)),
                ('student_realname', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(default='000', max_length=100, null=True)),
                ('salt', models.CharField(max_length=8, null=True)),
                ('thu_email', models.CharField(max_length=50, null=True)),
                ('profile_photo', models.ImageField(null=True, upload_to='')),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Team')),
            ],
        ),
    ]
