# Generated by Django 2.1 on 2018-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('game_name', models.CharField(max_length=50)),
                ('submission_start', models.DateTimeField()),
                ('submission_end', models.DateTimeField()),
            ],
        ),
    ]
