# Generated by Django 2.1 on 2019-03-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190314_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='id_map',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='battle',
            name='initiator_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Team ID'),
        ),
    ]
