# Generated by Django 2.1 on 2019-03-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190323_1244'),
        ('backend', '0003_auto_20190323_1440'),
    ]

    operations = [
    ]
