# Generated by Django 2.1 on 2018-12-01 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181102_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalSettings',
            new_name='GlobalSetting',
        ),
    ]
