# Generated by Django 2.1 on 2018-12-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181201_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='submission_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='submission_start',
            field=models.DateTimeField(),
        ),
    ]
