# Generated by Django 2.1 on 2018-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20181201_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
