# Generated by Django 2.1 on 2019-02-23 06:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20181201_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='leader',
            new_name='captain',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='history',
            new_name='history_active',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='invite_code',
            new_name='invitecode',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='teamname',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='member3',
        ),
        migrations.AddField(
            model_name='team',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=8000, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='history_passive',
            field=models.CharField(default='[]', max_length=8000),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.CharField(default='[]', max_length=8000),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_num',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
