# Generated by Django 2.1 on 2019-03-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20190223_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.CharField(max_length=50, null=True, verbose_name='Captain'),
        ),
        migrations.AlterField(
            model_name='team',
            name='createAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=8000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='team',
            name='history_active',
            field=models.CharField(default='[]', help_text='Fighting history records of the team in JSON format.  If this is to be modified on django admin site, please make sure it retains valid in JSON format.', max_length=8000, verbose_name='Active fighting history'),
        ),
        migrations.AlterField(
            model_name='team',
            name='history_passive',
            field=models.CharField(default='[]', help_text='Fighting history records of the team in JSON format.  If this is to be modified on django admin site, please make sure it retains valid in JSON format.', max_length=8000, verbose_name='Passive fighting history'),
        ),
        migrations.AlterField(
            model_name='team',
            name='invitecode',
            field=models.CharField(max_length=20, null=True, verbose_name='Invitation code'),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_num',
            field=models.IntegerField(default=1, null=True, verbose_name='Members count'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.CharField(default='[]', help_text='Student IDs of team members in JSON array format.  If this is to be modified on django admin site, please make sure it retains valid in JSON format.', max_length=8000, verbose_name='Team members'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rank',
            field=models.IntegerField(default=999999),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='team',
            name='teamname',
            field=models.CharField(max_length=30, null=True, verbose_name='Team name'),
        ),
    ]
