# Generated by Django 2.1 on 2019-03-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190312_2149'),
        ('backend', '0012_battle_start_time'),
    ]

    operations = [
    ]
