# Generated by Django 2.1 on 2019-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_merge_20190313_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='result',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
