# Generated by Django 2.1 on 2019-03-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190313_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Battle ID'),
        ),
    ]
