# Generated by Django 2.1 on 2019-03-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battleId', models.IntegerField()),
                ('userId1', models.IntegerField()),
                ('userId2', models.IntegerField()),
                ('running', models.BooleanField()),
            ],
        ),
    ]
